export const timelineItems = [
  {
    title: 'Analysis of Prior Art and Trend Research',
    team: '3 researchers or analysts',
    timeDescription: '3 team members work 8 hours per day for 7 days',
    total: '7 Days / 168 hours',
    optimized: '128 hours',
    highlightTitle: 'Instant Audience Report with Neuromarketing Analysis Instant Automated Concept Testing w/ Neuromarketing Test Viewer Engagement Testing - Same day results',
    highlightDesc: 'Neuromarketing Analysis 24/7 Instant Request Same day results Demographic Alignment Automated',
  },
  {
    title: 'Initial Design and Concept Development',
    team: '3x Designers, 2x copywriters and creative director',
    timeDescription: '6 team members work 8 hours per 14 days',
    total: '14 Days / 672 hours',
    optimized: '504 hours',
    highlightTitle: 'Instant Audience Report with Neuromarketing Analysis Instant Automated Concept Testing w/ Neuromarketing Test Viewer Engagement Testing - Same day results',
    highlightDesc: 'Neuromarketing Analysis 24/7 Instant Request Same day results Demographic Alignment Automated',
  },
  {
    title: 'Creating the First Draft of the Multimedia Video',
    team: 'Directors, camera operators, sound technicians, actors/actresses, lighting technicians, script supervisors.',
    timeDescription: '17 team members work 8 hours per day for 21 days',
    total: '21 Days / 2,856 hours',
    optimized: '2,142 hours',
    highlightTitle: 'Interactive AI Full Scope Re-design Analysis Audio design and full sequencer designer',
    highlightDesc: 'Automated Media Auditor, Automated Compliance Mitigation, Neuromarketing Analysis/Testing, Measure Audience Engagement Automated',
  },
  {
    title: 'First Review and edits',
    team: 'Editors, director, producers',
    timeDescription: '7 team members work 8 hours per day for 7 days',
    total: '7 Days / 392 hours',
    optimized: '294 hours',
    highlightTitle: 'In Ad Actor Behavior Analysis to Audience Align - Same day results Neuromarketing analyzing actors in video - Same day results Instant Audience Report with Neuromarketing Analysis',
    highlightDesc: 'Ad Quality Automated Testing, Linguistic Analysis Automated, Market Reach Statistics, AV Full AI Designer',
  },
  {
    title: 'Subsequent Reviews and Edits',
    team: 'Editors, producers, creative director, and occasional consultations from designers and copywriters.',
    timeDescription: '7 team members work 8 hours for 7 days',
    total: '14 Days / 672 hours',
    optimized: '504 hours',
    highlightTitle: 'In Ad Actor Behavior Analysis to Audience Align - Same day results Neuromarketing analyzing actors in video - Same day results Instant Audience Report with Neuromarketing Analysis',
    highlightDesc: 'Ad Quality Automated Testing, Linguistic Analysis Automated, Market Reach Statistics, AV Full AI Designer',
  },
  {
    title: 'Compliance and Legal Clearance',
    team: 'Legal advisors or compliance officers.',
    timeDescription: '2 advisors work 8 hours per day for 5 days',
    total: '5 Days / 80 hours',
    optimized: '60 hours',
    highlightTitle: 'Ad Quality Automated Testing, Demographic Ethical Analysis - same day',
    highlightDesc: 'Linguistic Analysis Automated, Brand Contract Compliance report - same day, Market Reach Statistics, AV Full AI Designer, Full Neuromarketing Analysis/Testing - same day, Instant Audience Report with Neuromarketing Results',
  },
  {
    title: 'Final Review and Approval',
    team: 'Producers, director, senior executives for approval.',
    timeDescription: '5 team members work 8 hours per day for 3 days',
    total: '3 Days / 120 hours',
    optimized: '90 hours',
    highlightTitle: 'Ad Quality Automated Testing, Demographic Ethical Analysis - same day',
    highlightDesc: 'Linguistic Analysis Automated, Brand Contract Compliance report - same day, Market Reach Statistics, AV Full AI Designer, Full Neuromarketing Analysis/Testing - same day, Instant Audience Report with Neuromarketing Results',
  },
];